Repository Princess-in-silvertown/toyou-server, pull requests merged in 2024-07, with the labels that each got.

#9 ⚡ Feat : Define common api response
  src/main/java/slvtwn/khu/toyouserver/common/ApiResponse.java
  src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
  src/main/java/slvtwn/khu/toyouserver/common/PageInfoResponse.java
  src/main/java/slvtwn/khu/toyouserver/common/SuccessType.java
Labels: 🧾 API, ✨ feat, 🥵 hart

#14 Feat: 유저 조회 기능 및 테스트 구현
  src/main/java/slvtwn/khu/toyouserver/Member.java
  src/main/java/slvtwn/khu/toyouserver/common/ToyouResponse.java
  src/main/java/slvtwn/khu/toyouserver/user/controller/UserController.java
  src/main/java/slvtwn/khu/toyouserver/user/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/user/dto/UserResponse.java
  src/main/java/slvtwn/khu/toyouserver/user/exception/UserNotFoundException.java
  src/main/java/slvtwn/khu/toyouserver/user/repository/UserRepository.java
  src/main/java/slvtwn/khu/toyouserver/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/slvtwn/khu/toyouserver/user/service/UserServiceTest.java
Labels: ✨ feat

#18 Feat: 그룹 가입 기능 구현
  src/main/java/slvtwn/khu/toyouserver/Comment.java
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/common/BaseTimeEntity.java
  src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
  src/main/java/slvtwn/khu/toyouserver/domain/Comment.java
  src/main/java/slvtwn/khu/toyouserver/domain/Group.java
  src/main/java/slvtwn/khu/toyouserver/domain/Member.java
  src/main/java/slvtwn/khu/toyouserver/domain/RollingPaper.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/dto/GroupResponse.java
  src/main/java/slvtwn/khu/toyouserver/dto/UserResponse.java
  src/main/java/slvtwn/khu/toyouserver/exception/ToyouException.java
  src/main/java/slvtwn/khu/toyouserver/persistance/GroupRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
  src/main/java/slvtwn/khu/toyouserver/presentation/UserController.java
  src/main/java/slvtwn/khu/toyouserver/user/exception/UserNotFoundException.java
  src/main/java/slvtwn/khu/toyouserver/user/service/UserService.java
  src/main/resources/application.yml
  src/test/java/slvtwn/khu/toyouserver/user/service/UserServiceTest.java
Labels: 🧾 API, ✨ feat, 🥵 hart

#20 Feat: user 정보에 birthday 필드 추가
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/dto/UserResponse.java
  src/main/java/slvtwn/khu/toyouserver/presentation/UserController.java
  src/test/java/slvtwn/khu/toyouserver/user/service/UserServiceTest.java
Labels: ✨ feat, 😸 teo

#22 Feat: 그룹 내 전체 유저 조회
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/domain/MemberRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupMemberResponse.java
Labels: 🧾 API, ✨ feat, 🥵 hart

#24 Feat: 신규 그룹 생성 기능
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
  src/main/java/slvtwn/khu/toyouserver/dto/GroupCreateRequest.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
Labels: 🧾 API, ✨ feat, 🥵 hart

#27 ♻️ Refactor: ArgumentResolver를 통한 유저 인증 전처리
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/common/CookieAuthArgumentResolver.java
  src/main/java/slvtwn/khu/toyouserver/common/ErrorType.java
  src/main/java/slvtwn/khu/toyouserver/common/SessionUserService.java
  src/main/java/slvtwn/khu/toyouserver/common/UserAuthentication.java
  src/main/java/slvtwn/khu/toyouserver/common/WebConfig.java
  src/main/java/slvtwn/khu/toyouserver/domain/SessionUser.java
  src/main/java/slvtwn/khu/toyouserver/persistance/SessionUserRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/UserController.java
Labels: ♻️ refactor, 🧾 API, 😸 teo, 🥵 hart

#28 ✨ Feat: 그룹 소속 유저 조회 기능
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/application/MemberService.java
  src/main/java/slvtwn/khu/toyouserver/domain/Member.java
  src/main/java/slvtwn/khu/toyouserver/domain/MemberRepository.java
  src/main/java/slvtwn/khu/toyouserver/domain/SessionUser.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
  src/test/java/slvtwn/khu/toyouserver/application/GroupServiceTest.java
Labels: ♻️ refactor, 🧾 API, ✨ feat, ✅ test, 🥵 hart
