Repository Princess-in-silvertown/toyou-server, pull requests merged in 2024-09, with the labels that each got.

#44 Feat: 소셜 로그인 가입
  .github/ISSUE_TEMPLATE/issue--feat.md
  .github/ISSUE_TEMPLATE/issue--fix.md
  .github/ISSUE_TEMPLATE/issue--refactor.md
  .github/pull_request_template.md
  .github/workflows/ci-develop.yml
  build.gradle
  src/main/java/slvtwn/khu/toyouserver/common/authentication/JWTAuthArgumentResolver.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/JwtAuthenticationEntryPoint.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/SecurityWhiteListPaths.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/UserEntityAuthentication.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/filter/ExceptionHandlerFilter.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/filter/JwtAuthenticationFilter.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/jwt/JwtGenerator.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/jwt/JwtProvider.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/jwt/JwtValidator.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/jwt/Token.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/SocialAuthContext.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/KakaoAuthStrategy.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/SocialAuthStrategy.java
  src/main/java/slvtwn/khu/toyouserver/common/configuration/FeignConfig.java
  src/main/java/slvtwn/khu/toyouserver/common/configuration/SecurityConfig.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/KakaoAuthApiClient.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/KakaoResourceApiClient.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/web/KakaoAccount.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/web/KakaoTokenResponse.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/web/KakaoUserProfile.java
  src/main/java/slvtwn/khu/toyouserver/common/feign/auth/kakao/web/KakaoUserResponse.java
  src/main/java/slvtwn/khu/toyouserver/common/response/ResponseType.java
  src/main/java/slvtwn/khu/toyouserver/domain/SocialAuthProvider.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/dto/SocialAuthRequest.java
  src/main/java/slvtwn/khu/toyouserver/dto/SocialAuthResponse.java
  src/main/java/slvtwn/khu/toyouserver/exception/UnauthorizedException.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/AuthController.java
  src/main/resources/application.yml
Labels: 🧾 API, ✨ feat

#47 Refactor: 변경된 API에 맞게 기능 수정
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
  src/main/java/slvtwn/khu/toyouserver/presentation/MemberController.java
  src/main/java/slvtwn/khu/toyouserver/presentation/UserController.java
  src/test/resources/application.yml
Labels: ♻️ refactor, 🧾 API

#48 Feat: 커버이미지 생성 기능
  src/main/java/slvtwn/khu/toyouserver/agent/WebClientWrapper.java
  src/main/java/slvtwn/khu/toyouserver/agent/gpt/ChatGptAgent.java
  src/main/java/slvtwn/khu/toyouserver/agent/modellabs/MetaDataResponse.java
  src/main/java/slvtwn/khu/toyouserver/agent/modellabs/ModelLabsAgent.java
  src/main/java/slvtwn/khu/toyouserver/agent/modellabs/ModelLabsConfiguration.java
  src/main/java/slvtwn/khu/toyouserver/agent/modellabs/ModelLabsRequest.java
  src/main/java/slvtwn/khu/toyouserver/agent/modellabs/ModelLabsResponse.java
  src/main/java/slvtwn/khu/toyouserver/application/RollingPaperService.java
  src/main/java/slvtwn/khu/toyouserver/domain/RollingPaper.java
  src/main/java/slvtwn/khu/toyouserver/dto/CoverRequest.java
  src/main/java/slvtwn/khu/toyouserver/persistance/RollingPaperRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/RollingPaperController.java
  src/main/resources/application.yml
  src/test/resources/application.yml
Labels: 🧾 API, ✨ feat

#49 Feat: 롤링페이퍼 단일 조회, 발신 기능
  src/main/java/slvtwn/khu/toyouserver/application/EventService.java
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/application/RollingPaperService.java
  src/main/java/slvtwn/khu/toyouserver/application/SessionService.java
  src/main/java/slvtwn/khu/toyouserver/domain/Comment.java
  src/main/java/slvtwn/khu/toyouserver/domain/RollingPaper.java
  src/main/java/slvtwn/khu/toyouserver/domain/Sticker.java
  src/main/java/slvtwn/khu/toyouserver/domain/StickerSide.java
  src/main/java/slvtwn/khu/toyouserver/dto/CoverRequest.java
  src/main/java/slvtwn/khu/toyouserver/dto/RollingPaperRequest.java
  src/main/java/slvtwn/khu/toyouserver/dto/RollingPaperResponse.java
  src/main/java/slvtwn/khu/toyouserver/dto/StickerRequest.java
  src/main/java/slvtwn/khu/toyouserver/dto/StickerResponse.java
  src/main/java/slvtwn/khu/toyouserver/persistance/MemberRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/StickerRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/RollingPaperController.java
Labels: ♻️ refactor, 🧾 API, ✨ feat, 😸 teo, 🥵 hart

#57 Feat: 이름 키워드 기반 학교 검색 기능
  src/main/java/slvtwn/khu/toyouserver/application/SchoolSearchService.java
  src/main/java/slvtwn/khu/toyouserver/domain/School.java
  src/main/java/slvtwn/khu/toyouserver/dto/SchoolSearchResponse.java
  src/main/java/slvtwn/khu/toyouserver/external/search/school/client/CareerNetSchoolSearchClient.java
  src/main/java/slvtwn/khu/toyouserver/external/search/school/web/CareerNetSchoolResult.java
  src/main/java/slvtwn/khu/toyouserver/persistance/SchoolRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/SchoolController.java
  src/main/resources/application.yml
  src/test/java/slvtwn/khu/toyouserver/application/SchoolSearchServiceTest.java
Labels: 🧾 API, ✨ feat, ✅ test, 🥵 hart

#62 Feat: 단위/통합 테스트 작성
  src/main/java/slvtwn/khu/toyouserver/application/EventService.java
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/application/SessionService.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/CookieAuthArgumentResolver.java
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/KakaoAuthStrategy.java
  src/main/java/slvtwn/khu/toyouserver/common/configuration/WebConfig.java
  src/main/java/slvtwn/khu/toyouserver/domain/Event.java
  src/main/java/slvtwn/khu/toyouserver/domain/Member.java
  src/main/java/slvtwn/khu/toyouserver/domain/Session.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/dto/EventResponse.java
  src/main/java/slvtwn/khu/toyouserver/persistance/SessionRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserRepository.java
  src/test/java/slvtwn/khu/toyouserver/application/EventServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/GroupServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/RollingPaperServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/UserServiceTest.java
Labels: ✅ test, 😸 teo

#79 Feat: 유저 프로필 조회 파사드 생성
  src/main/java/slvtwn/khu/toyouserver/application/UserProfileFacade.java
  src/main/java/slvtwn/khu/toyouserver/dto/UserProfileResponse.java
  src/main/java/slvtwn/khu/toyouserver/presentation/UserController.java
  src/test/java/slvtwn/khu/toyouserver/application/EventServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/GroupServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/RollingPaperServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/UserServiceTest.java
Labels: 🧾 API, ✨ feat

#81 Fix: 학교 정보 및 그룹 정보 병합, 테스트 수정
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/application/SchoolSearchService.java
  src/main/java/slvtwn/khu/toyouserver/application/UserProfileFacade.java
  src/main/java/slvtwn/khu/toyouserver/domain/Group.java
  src/main/java/slvtwn/khu/toyouserver/domain/School.java
  src/main/java/slvtwn/khu/toyouserver/dto/SchoolSearchResponse.java
  src/main/java/slvtwn/khu/toyouserver/persistance/GroupRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/SchoolRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/GroupController.java
  src/main/java/slvtwn/khu/toyouserver/presentation/SchoolController.java
  src/test/java/slvtwn/khu/toyouserver/application/GroupServiceTest.java
  src/test/java/slvtwn/khu/toyouserver/application/SchoolSearchServiceTest.java
Labels: ♻️ refactor, 🐛 bug, 😸 teo

#84 Refactor: 학교 검색결과 최소 Limit 설정
  src/main/java/slvtwn/khu/toyouserver/application/GroupService.java
  src/main/java/slvtwn/khu/toyouserver/persistance/GroupRepository.java
Labels: ♻️ refactor, ✨ feat, 🥵 hart

#86 Refactor: 사용자 중복 OAuth 로그인 검증 로직
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/KakaoAuthStrategy.java
  src/main/java/slvtwn/khu/toyouserver/domain/UserSocialAccount.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserSocialAccountRepository.java
Labels: ♻️ refactor, 🧾 API, ✨ feat

#85 Feat: 수신된 롤링페이퍼 그룹 필터링 기반 조회 기능
  src/main/java/slvtwn/khu/toyouserver/application/RollingPaperService.java
  src/main/java/slvtwn/khu/toyouserver/common/response/ResponseType.java
  src/main/java/slvtwn/khu/toyouserver/persistance/RollingPaperRepository.java
  src/main/java/slvtwn/khu/toyouserver/presentation/RollingPaperController.java
  src/test/java/slvtwn/khu/toyouserver/application/RollingPaperServiceTest.java
Labels: ♻️ refactor, 🧾 API, ✨ feat, ✅ test, 🥵 hart

#90 Refactor: 사용자 소셜 가입 정보 User 도메인 통합
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/KakaoAuthStrategy.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
  src/main/java/slvtwn/khu/toyouserver/domain/UserSocialAccount.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/UserSocialAccountRepository.java
Labels: ♻️ refactor

#91 Hotfix: 카카오 로그인 디버깅 환경 분리
  src/main/java/slvtwn/khu/toyouserver/common/authentication/social/strategy/KakaoAuthStrategy.java
Labels: 🚑 HOTFIX

#98 Fix: 유저 이름을 이벤트 이름으로 설정
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
Labels: ♻️ refactor, 😸 teo

#99 Refactor: 프롬프트 수정
  src/main/java/slvtwn/khu/toyouserver/application/AgentService.java
Labels: ♻️ refactor, 😸 teo
