Repository Princess-in-silvertown/toyou-server, pull requests merged in 2024-10, with the labels that each got.

#104 Refactor: 그룹 변경 시 관련 롤링페이퍼 역시 삭제하도록 변경
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/persistance/RollingPaperRepository.java
Labels: ♻️ refactor, 😸 teo

#105 Refactor: 롤링페이퍼 발신자 정보 추가
  src/main/java/slvtwn/khu/toyouserver/application/RollingPaperService.java
  src/main/java/slvtwn/khu/toyouserver/domain/RollingPaper.java
  src/main/java/slvtwn/khu/toyouserver/domain/SenderSnapshot.java
  src/main/java/slvtwn/khu/toyouserver/dto/RollingPaperResponse.java
  src/main/java/slvtwn/khu/toyouserver/presentation/RollingPaperController.java
  src/test/java/slvtwn/khu/toyouserver/application/RollingPaperServiceTest.java
Labels: ♻️ refactor, 😸 teo

#107 Fix: 그룹 일부 삭제 시 롤링페이퍼를 소유하고 있다면 오류가 발생하던 문제 수정
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/persistance/GroupRepository.java
  src/main/java/slvtwn/khu/toyouserver/persistance/MemberRepository.java
  src/test/java/slvtwn/khu/toyouserver/application/UserServiceTest.java
Labels: 🐛 bug, 😸 teo

#109 :bug: fix: 중복 사용자를 반환하지 않도록 수정
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/main/java/slvtwn/khu/toyouserver/domain/User.java
Labels: 🐛 bug, 😸 teo

#111 :bug: fix: 그룹 삭제가 제대로 이루어지지 않던 문제 해결
  src/main/java/slvtwn/khu/toyouserver/application/UserService.java
  src/test/java/slvtwn/khu/toyouserver/application/UserServiceTest.java
Labels: 🐛 bug, 😸 teo

#115 [Fix] 메시지함 Paging 속성 계산 오류
  src/main/java/slvtwn/khu/toyouserver/application/RollingPaperService.java
  src/main/java/slvtwn/khu/toyouserver/dto/CursorPageInfo.java
  src/main/java/slvtwn/khu/toyouserver/persistance/RollingPaperRepository.java
  src/test/java/slvtwn/khu/toyouserver/application/RollingPaperServiceTest.java
Labels: 🐛 bug, ✅ test
